import { Routes } from '@angular/router';
import { AddCustomersFormComponent } from 'src/app/customers/add-customers-form/add-customers-form.component';
import { CustomersComponent } from 'src/app/customers/customers.component';
import { DashboardComponent } from 'src/app/dashboard/dashboard/dashboard.component';
import { AddProjectFormComponent } from 'src/app/projects/add-project-form/add-project-form.component';
import { ProjectsComponent } from 'src/app/projects/projects/projects.component';
import { ReportsComponent } from 'src/app/reports/reports/reports.component';
import { GroupsComponent } from 'src/app/settings/groups/groups.component';
import { RolesComponent } from 'src/app/settings/roles/roles.component';
import { AddSprintFormComponent } from 'src/app/sprints/add-sprint-form/add-sprint-form.component';
import { SprintsComponent } from 'src/app/sprints/sprints/sprints.component';
import { AddTaskFormComponent } from 'src/app/tasks/add-task-form/add-task-form.component';
import { ListOfTasksComponent } from 'src/app/tasks/list-of-tasks/list-of-tasks.component';
import { TimeCardsComponent } from 'src/app/time-cards/time-cards/time-cards.component';
import { AddUserFormComponent } from 'src/app/users/add-user-form/add-user-form.component';
import { UsersComponent } from 'src/app/users/users/users.component';

export const AdminLayoutRoutes: Routes = [
    { path: 'dashboard', component: DashboardComponent },
    { path: 'customers', component: CustomersComponent },
    { path: 'users', component: UsersComponent },
    { path: 'projects', component: ProjectsComponent },
    { path: 'sprints', component: SprintsComponent },
    { path: 'tasks', component: ListOfTasksComponent },
    { path: 'time-cards', component: TimeCardsComponent },
    { path: 'reports', component: ReportsComponent },
    { path: 'settings/roles', component: RolesComponent },
    { path: 'settings/groups', component: GroupsComponent },
    { path: 'add-customer-form', component: AddCustomersFormComponent },
    { path: 'add-user-form', component: AddUserFormComponent },
    { path: 'add-project-form', component: AddProjectFormComponent },
    { path: 'add-task-form', component: AddTaskFormComponent },
    { path: 'add-sprint-form', component: AddSprintFormComponent },
];
